<div style="display:inline">第557节</div><details style="color:orange;display:inline"><summary></summary>SESSION 557,</details><br>
<div style="display:inline">1970年10月28日 星期三 晚上9：19</div><details style="color:orange;display:inline"><summary></summary>OCTOBER 28, 1970, 9:19 P.M. WEDNESDAY</details><br>
<div style="display:inline">(我解释我的两个问题给珍听，并不一定期望赛斯今晚提到它。</div><details style="color:orange;display:inline"><summary></summary>(I had two questions which I explained to Jane, without necessarily expecting Seth to go into them tonight.</details><br>
<div style="display:inline">(一、在第556节，赛斯说，许多写历史文章的作者是从他们直接的前世经验来写的。我的问题是关乎一个假设的实验，好比说拿一百位这种作者来作个实验，把他们催眠而不告诉他们实验的目的，一旦被催眠了，就问他们有关前生记忆的问题。我猜想不知他们中百分之几的人会回忆起任何事，而这种试验不知可否提供作为转世的明证。</div><details style="color:orange;display:inline"><summary></summary>(1.?In the 556th session, Seth said that many writers of historical pieces are writing out of direct Past-life experience. My question concerned a hypothetical experiment in which, say, a hundred such writers would be hypnotized without being told what the purpose of the experiment was; once under, they would be queried about Past-life memories. I wondered what percentage of them would recall any, and if such a test might furnish good evidence for reincarnation.</details><br>
<div style="display:inline">(二、当一个非肉体的人格决定第一次投生于肉体中时，他有哪些可用的过程？最初的生活是什么样子？是否比较容易有野蛮的倾向？或在某程度更“有教养”？或究竟有没有涉及任何预定的模式(predetermined pattern)？</div><details style="color:orange;display:inline"><summary></summary>(2.?What procedures are available to the nonphysical personality when it decides to incarnate physically for the first time? What is the initial life like? Is it apt to be savage, or more “cultivated” to some degree? Or is any sort of predetermined pattern involved at all?</details><br>
<div style="display:inline">(既然我对这些问题已好奇了一阵子，我想赛斯著作的读者也可能会有同感。没想到，事情的发展是，赛斯对第一个问题全没注意，而以一种最有趣的方式由第二个问题谈起。</div><details style="color:orange;display:inline"><summary></summary>(Since I’ve been curious about these questions for some time, I thought the readers of Seth’s book might be also. As things develop, however, Seth doesn’t pay any attention to the first question now, and takes off from the second one in a most interesting way.</details><br>
<div style="display:inline">(在今晚的课开始之前，我才在猜测说，如果这个月珍没在看那本包含了瑞士精神分析家荣格的一篇文章的文集，那不知第十三章会是什么样子。如我提过的，在10月19日珍还没有时间看完它之前，赛斯建议珍把那本书搁在一边。见10月21日第555节一开始时的注。此后我们俩都没有再看那本书。</div><details style="color:orange;display:inline"><summary></summary>(Just before the session tonight I wondered aloud what the present Chapter Thirteen would have been like if Jane hadn’t begun to read, early this month, the anthology containing the long section by Carl Jung, the Swiss psychoanalyst. As I mentioned, Seth suggested Jane lay the book aside on October 19, before she had time to finish it. See the notes at the beginning of the 555th session for October 21. Neither of us has looked at the book since.</details><br>
<div style="display:inline">(在此章中突然出现了荣格的影响——虽然是以赛斯自己的方式处理的。但在我们自己生活中的事件也曾影响了此书的每一章。每一章的特定形式，都可能多少受到为此章而举行的课是在何时举行，以及它所谈及主题本身的影响。于是，甚至干扰也有其作用……)</div><details style="color:orange;display:inline"><summary></summary>(An infusion from Jung cropped up in this chapter, of course ---- although handled in Seth’s own way. But then such events in our own lives have influenced every other chapter in the book, too. The particular form of a chapter could be affected to some degree by just when the sessions for it were held, as well as by its intrinsic subject matter. Even interruptions, then, would play their part….)</details><br>
<div style="display:inline">晚安。</div><details style="color:orange;display:inline"><summary></summary>Good evening.</details><br>
<div style="display:inline">(“赛斯晚安”)</div><details style="color:orange;display:inline"><summary></summary>(“Good evening, Seth.”)</details><br>
<div style="display:inline">(欢喜而开心地：)我真高兴你赞同我的书。</div><details style="color:orange;display:inline"><summary></summary>(Pleased and amused): Now I am glad that you approve of my book.</details><br>
<div style="display:inline">(“我认为它很棒！”)</div><details style="color:orange;display:inline"><summary></summary>(“I think it’s great.”)</details><br>
<div style="display:inline">还有许多没说的呢！</div><details style="color:orange;display:inline"><summary></summary>There is much more in store.</details><br>
<div style="display:inline">(“太好了。”)</div><details style="color:orange;display:inline"><summary></summary>(“Very good.”)</details><br>
<div style="display:inline">因为这是一件活生生的工作，所以我们利用那些在你们自己生活里发生的事，首先就是我本人促使鲁柏拣起那本(包括有荣格的文章)书的。</div><details style="color:orange;display:inline"><summary></summary>Now this is a living endeavor, and therefore we take advantage of those happenings in your own lives, and it was I myself who prompted Ruburt to pick up the book (containing Jung) in the first place.</details><br>
<div style="display:inline">(“我没想到那一层。”我确知珍也没有。)</div><details style="color:orange;display:inline"><summary></summary>(“I hadn’t thought of that.” Nor, I was sure, had Jane.)</details><br>
<div style="display:inline">然后，在他看了这么多之后，我要他把书搁下等以后再说。(停顿)我们将继续口述。</div><details style="color:orange;display:inline"><summary></summary>Then, I wanted him to put it aside for another time, after he had read so far. (Pause.) We will resume dictation.</details><br>
<div style="display:inline">(可是，在此刻赛斯要我暂且把笔记放在一边，说他很遗憾在课中我得那么忙碌地记录。我们聊了一会儿，非常愉快的交谈。珍的眼睛又大又黑，她的传述很活泼；很容易叫人感觉到赛斯就在身边。这插曲少于一分钟。在9:20继续。)</div><details style="color:orange;display:inline"><summary></summary>(At this point, however, Seth requested that I lay my notebook aside for a bit, saying he regretted that I was kept so busy writing during sessions. We had a brief chat, a very pleasant exchange. Jane’s eyes were wide and dark, her delivery lively; it was easy to sense the immediacy of Seth’s presence. The interlude lasted less than a minute. Resume dictation at 9:20.)</details><br>
<div style="display:inline">组合成胎儿的原子有它们自己那一种意识。独立存在于物质之外的易变的“知觉—意识”，按照它们的能力和程度形成物质。因此，胎儿有它自己的意识，即由组成胎儿的原子所组成的简单构成意识(component consciousness)。这在任一转世的人格进入它之前就已存在。任何物质之中——一个胎儿、一块岩石、一片草叶、一个铁钉，都有物质的意识存在。</div><details style="color:orange;display:inline"><summary></summary>The atoms that compose the fetus have their own kind of consciousness. The volatile awareness-consciousnesses that exist independently of matter, form matter according to their ability and degree. The fetus, therefore, has its own consciousness, the simple component consciousness made up of the atoms that compose it. This exists before any reincarnating personality enters it. The consciousness of matter is present in any matter ---- a fetus, a rock, a blade of grass, a nail.</details><br>
<div style="display:inline">转世人格，按照它自己的倾向、愿望与特性，并且带着一些预先植入的保障进入新胎儿。但是并没有定规说转世人格必得接管为它所准备的新形体，不管是在受孕时、在胎儿成长的最初期、或甚至在出生的那一刻。</div><details style="color:orange;display:inline"><summary></summary>The reincarnating personality enters the new fetus according to its own inclinations, desires, and characteristics, with some built-in safeguards. However there is no rule, then, saying that the reincarnating personality must take over the new form prepared for it either at the point of conception, in the very earliest months of the fetus’s growth, or even at the point of birth.</details><br>
<div style="display:inline">其过程是渐进的、因人而异的，并且是由其他世的经验来决定；它特别依赖情感上的特性——不一定是由最近的前一生的自己，而是由许多过往的人生所导致的现有情感上的张力。</div><details style="color:orange;display:inline"><summary></summary>The process is gradual, individual and determined by experience in other lives. It is particularly dependent upon emotional characteristics ---- not necessarily of the last incarnated self, but the emotional tensions present as a result of a group of past existences.</details><br>
<div style="display:inline">(9:32暂停)有各种不同的入胎方法被采用。如果在父母与未来的孩子之间有很深的关系，如果他极渴望再与他们重聚，那么人格可能在受孕时便入胎了。不过，即使在这种情况，大部分的自我知觉(self-awareness)仍继续在两次生命之间的次元运作。</div><details style="color:orange;display:inline"><summary></summary>(Pause at 9:32.) Various methods of entry are adopted. If there is a strong relationship between the parents and the child-to-be, then the personality may enter at the point of conception if he is extremely anxious to rejoin them. Even here, however, large portions of self-awareness continue to operate in the between-life dimension.</details><br>
<div style="display:inline">最初，在这些情况之下，他在子宫里的状态就像做梦一样，人格仍旧集中焦点在两生之间的存在里。逐渐的，情形反过来了，直到他想要对两生之间的情形维持清晰的集中变得更难。</div><details style="color:orange;display:inline"><summary></summary>In the beginning, the womb state under these conditions is a dreamlike one, with the personality still focused mainly in the between-life existence. Gradually the situation reverses, until it becomes more difficult to retain clear concentration in the between-life situation.</details><br>
<div style="display:inline">在这些当人格在受孕时就入了胎的情形，几乎无一例外的，在父母与孩子间有很深的前世渊源，或者有一种不断的、几乎是执迷般的回返尘世的欲望——若非为了一个特定的目的，就是因为转世人格仍着迷于尘世的生活。这并非必然是不利的。这人格可能只是体认到它很喜欢肉体经验，目前是“心向尘寰”的，而觉得尘世氛围是可供它能力成长的丰富次元。</div><details style="color:orange;display:inline"><summary></summary>In these circumstances, when the personality attaches itself at conception, there is almost without exception strong Past-life connections between parents and child, or there is an unceasing and almost obsessional desire to return to the earthly situation ---- either for a specific purpose, or because the reincarnating personality is presently obsessed with earthly existence. This is not necessarily detrimental. The personality can simply realize that it takes to physical experience well, is presently earth-oriented, and finds earthly atmosphere a rich dimension for the growth of its own abilities.</details><br>
<div style="display:inline">有些人格在受孕时受到吸引而入胎，是由于一个看起来较无价值的动机——譬如贪婪，或是有部分由没解决的问题所组成萦绕不去的欲望。另外还有些从未全心投入尘世生活的人格，可能拖延一会儿才完全入胎，甚至入胎后还一直与身体保持一个距离。在天秤的另一端，人死前也会有同样的情形。那时有些人把他们的焦点自物质生活移开，只单单留下身体的意识。其他人则与肉体留在一起直到最后一刻。无论如何，在婴儿的襁褓时期，人格的焦点并没有稳定的集中在肉体内。</div><details style="color:orange;display:inline"><summary></summary>Some personalities are drawn to enter at conception as a result of seemingly less worthy motives ---- greed, for example, or an obsessional desire that is partially composed of unresolved problems. Other personalities who never completely take to earthly existence may hold off full entry for some time, and even then always remain at a certain distance from the body. At the other end of the scale, before death the same applies, where some individuals remove their focus from physical life, leaving the body consciousness alone. Others stay with the body until the last moment. In the early days of infancy, there is not a steady focus of the personality in the body in any case.</details><br>
<div style="display:inline">休息一下。我们再继续。</div><details style="color:orange;display:inline"><summary></summary>Take your break and we will continue.</details><br>
<div style="display:inline">(9:47—10:00)</div><details style="color:orange;display:inline"><summary></summary>(9:47 to 10:00.)</details><br>
<div style="display:inline">如我告诉过你们的，在所有的情形，决定是预先作好的。因此，当它所等待的受孕发生时，转世人格是知道的。虽则它可能选择要或不要在那一刻入胎，它仍是无法抗拒的被吸引到那个时间，以及那个现场。</div><details style="color:orange;display:inline"><summary></summary>Now: In all cases the decisions have been made ahead of time, as I told you. The reincarnating personality is aware, therefore, when the conception for which it has been waiting takes place. And while it may or may not choose to enter at that point, it is drawn irresistibly to that time and point in space and flesh.</details><br>
<div style="display:inline">偶尔，早在受孕发生之前，那个将会成为未来小孩的人格会探访未来双亲的环境，这又是被吸引过去的。这是十分自然的。</div><details style="color:orange;display:inline"><summary></summary>On occasion, long before conception takes place, the personality who will end up as the future child will visit that environment of both parents-to-be, drawn again. This is quite natural.</details><br>
<div style="display:inline">在两世之间，一个人可能看到来生情景的闪现，不一定是看到什么特定的事件，而是体验到新关系的精髓所在，而在期待中提醒自己他自设的挑战。这样说来，在你家中“未来的鬼”就与“过去的鬼”一样真实。</div><details style="color:orange;display:inline"><summary></summary>Between lives an individual may see flashes of the future existence, not necessarily of particular events, but experience the essence of the new relationship and in expectation remind himself of the challenge he has set. In these terms, the ghosts of the future are as real in your homes as the ghosts of the past.</details><br>
<div style="display:inline">你并没有一个全空的物质的壳等着被填满，因为新的人格常常在里面或附近飞翔，特别是在受孕后，以后频率与强度更渐增加。可是，出生的震撼有几种后果，通常会把这人格可谓一下子完全拖进物质实相。在此之前，情况是相当的单调，身体意识几乎是自动地受到滋养，反应很强烈，却是在高度控制的情况之下。</div><details style="color:orange;display:inline"><summary></summary>You do not have completely empty shells of matter about to be filled, in that the new personality hovers in and about, particularly after conception and with greater frequency and intensity thereafter. The shock of birth has several consequences, however, that usually draw the personality full blast, so to speak, into physical reality. Before this, the conditions are fairly uniform. The body consciousness is nurtured almost automatically, reacting strongly but under highly controlled conditions.</details><br>
<div style="display:inline">在出生时，所有的这些都突然完结了，〔新的〕刺激，〔被〕这么快速的引进，是身体意识到此时为止从未经验过的。</div><details style="color:orange;display:inline"><summary></summary>At birth, all of this is suddenly over, and [new] stimuli [are] introduced with a rapidity that the body consciousness has never to that point experienced.</details><br>
<div style="display:inline">(10:10)它极需一个使它安定的因素。原先，身体意识由于和母亲在生理上与心电感应上很深的认同，而得到滋养与支持。在细胞间的沟通远比你想象的要深沉。如果只考虑到身体意识，则其认同在出生前几乎是完全的。</div><details style="color:orange;display:inline"><summary></summary>(10:10.) It greatly needs a stabilizing factor. Previously the body consciousness has been enriched and supported by deep biological and telepathic identification with the mother. The communication of the living cells is far more profound than you imagine. The identification is almost complete before birth as far as body consciousness alone is concerned.</details><br>
<div style="display:inline">在新的人格进入之前，胎儿一直认它自己为母体的一部分。在出生时，这种支持却遭到突然的否认。如果在这以前新的人格没有完全进入，它通常在出生时这样做，以稳定新的有机体。换言之，它安抚新的有机体。因此，新的人格按照它何时进入这次元，而以不同的程度体验出生的过程。</div><details style="color:orange;display:inline"><summary></summary>Until the new personality enters, the fetus regards itself as a part of the organism of the mother. This support is suddenly denied at birth. If the new personality has not entered earlier to any full extent, it usually does so at birth, in order to stabilize the new organism. It comforts the new organism, in other words. The new personality, therefore, will experience birth to varying degrees according to when it has entered this dimension.</details><br>
<div style="display:inline">当它在出生那一刻入胎，它还是相当独立的，尚未与它所进入的形体认同，而是扮演支持性的角色。如果人格在受孕时或出生前的什么时间入胎，那么它就多少与胎儿的身体意识认同了。它已开始指挥知觉——虽然不管有没有受到这种指挥，知觉都已开始了——它将以最切身、直接的方式经历出生的震撼。</div><details style="color:orange;display:inline"><summary></summary>When it enters at the point of birth, it is fairly independent, not yet identified with the form it has entered, and acting in a supportive role. If the personality entered at conception or sometime before birth, then it has to some extent identified with the body consciousness, with the fetus. It has already begun to direct perception ---- though perception has begun whether or not it is so directed ---- and it will experience the shock of birth in immediate, direct terms.</details><br>
<div style="display:inline">(10:19)这样的话，在人格与出生经验之间就没有距离。新进入婴儿的人格，做为一个意识，是闪烁不定的，因为在达到稳定之前还有一段时间。当这孩子，特别是幼儿，在睡觉时，举例来说，人格常常就离开了身体。逐渐地，它与两世之间的情况认同减少了，直到它几乎全部的焦点都定居在肉体之内。</div><details style="color:orange;display:inline"><summary></summary>(10:19.) There will be no distance between the personality and the experience of birth, then. The newly entered personality, as a consciousness, flickers, in that there is a while before stabilization takes place. When the child, particularly the young child, is sleeping, for example, the personality often simply vacates the body. Gradually the identification with the between-life situation dwindles until nearly full focus resides in the physical body.</details><br>
<div style="display:inline">显然有些人比其他人与身体的认同更完全得多。一般说来，对物质实相的集中焦点，有一个最适宜的时间，一段强化，与时间的长短无干，可以长达一周或三十年。从那以后它开始减弱，不知不觉地开始转移到其他的实相层面。</div><details style="color:orange;display:inline"><summary></summary>There are obviously those who identify with the body far more completely than others. Generally speaking, there is an optimum point of focus in physical reality, a period of intensification that has nothing to do with duration. It can last for a week or thirty years, and from then onward it begins to dwindle, and imperceptibly begins to shift to other layers of reality.</details><br>
<div style="display:inline">一个危机可能如此地损毁了这人与其身体的认同感，以致他暂时离开了身体，尤其是当危机发生在人生的最早期或最晚期时。于是他可能有几种反应：如果身体意识也受到震惊的话，他可能离开得如此完全以致身体进入了昏迷状态。如果震惊是心理上的，而身体意识仍或多或少正常地运作，那他可能回归成一个早先的转世人格。</div><details style="color:orange;display:inline"><summary></summary>Now. A crisis, particularly in very early or very late life, may so shatter the personality’s identification with the body that he vacates it temporarily. He may do one of many things. He may leave so completely that the body goes into coma, if the body consciousness has also suffered shock. If the shock is psychological and the body consciousness is still operating more or less normally, then he may revert to an earlier reincarnational personality.</details><br>
<div style="display:inline">在这种情形，这只是一个倒退，常会过去的。此地我们再度关切到男灵与女灵的问题。如果一个人格相信它在男性生涯做得很差劲，它可能会发动女灵的特质，采取一个它很成功的过去女性生涯里的特性。把那个画面反过来，同样的事也可能发生在一个女人身上。</div><details style="color:orange;display:inline"><summary></summary>缺</details><br>
<div style="display:inline">(10:30)在另外一方面，如果这人格发现它曾与它现在的性别过分认同，以致深深地威胁了它的个人性，那么它也可能把相反的画面搬到显著的地位，做得这么过分以致又去与那相反性别的过去人格相认同。</div><details style="color:orange;display:inline"><summary></summary>(10:30.) On the other hand, if the personality finds that it has so over-identified with its present sex that its individuality is deeply threatened, then it may also bring to the fore the opposite picture, going so far as to identify again with a past personality of the opposite sex.</details><br>
<div style="display:inline">在早年人格对身体的把持是很微弱的，但渐渐会增强。人格为了它自己的理由，可能决定选择一个在美观上来说不可爱的身体。他可能从不觉得与它有关联，而虽然这一次的人生能达到他心中预存的目的，在这身体与它内的人格之间总有一个基本可感觉到的距离。</div><details style="color:orange;display:inline"><summary></summary>The hold of the personality over the body is tenuous in the early years, and grows stronger. The personality, for its own reasons, may decide upon choosing a body that is not aesthetically pleasing. He may never relate to it, and while the existence will serve what purposes he had in mind, there will always be a basic sensed distance between the body and the personality within it.</details><br>
<div style="display:inline">先前所说那些在受孕时就入胎的人格，通常都非常渴望人间生活。因此，他们会更完全地发展，并且很早便显出他们个人的特性。他们抓住新的身体就已开始塑造它。对物质的控制是非常有力的，而他们通常留在身体内，不是在意外事件中立即死亡，就是在睡眠中死去，或者死于急病。一般而言，他们是物质的操纵者。</div><details style="color:orange;display:inline"><summary></summary>Those mentioned earlier who enter at the point of conception are usually highly anxious for physical existence. They will, therefore, be more fully developed and show their individual characteristics very early. They seize upon the new body and already mold it. The control over matter is vigorous, and they usually stay within the body, dying either in accidents where death is immediate or in sleep or with a disease that strikes quickly. They are manipulators of matter as a rule.</details><br>
<div style="display:inline">(10:40)他们是感情用事的，他们常以即刻的、迫不及待的、明确的方式解决他们的问题。他们善用大地的材料，把他们的概念非常有力的转译成物质的形式。他们建造城市、纪念碑。他们是建筑师。他们关切的是形成物质并且照他们的愿望塑造它。</div><details style="color:orange;display:inline"><summary></summary>(10:40.) They are emotional. They work out their problems in immediate, sometimes impatient, tangible ways. They work well with earth materials, and translate their ideas with great force into physical terms. They make cities, monuments. They are architects. They are concerned with forming matter and molding it to their desire.</details><br>
<div style="display:inline">一般而言，那些直到出生那一刻才进入你们存在层面的人，在那些特定的方面来说是比较没有那么行的操纵者，如果可以这么说的话，他们是平庸之辈或普通人。</div><details style="color:orange;display:inline"><summary></summary>As a rule, now, those who do not enter your plane of existence until the point of birth are less able manipulators in those particular terms. They are the mean, if such a term can be used, the mean or average.</details><br>
<div style="display:inline">至于还有些人则尽可能地抗拒这新的人生，即使他们选择了它。他们多少必须在出生时在场，但他们仍能避免与新生儿有任何完全的认同。他们在那形体之内或四周飞来飞去，半带着勉强。这种行为有许多原因。有些人格只是较喜欢“两世之间”的存在而已，而且对理论性的解决问题比必须涉及的实际应用要关心得多。另一些人发现，人世生活并不如他们想象那样满足他们的需要，而他们在另一个实相与存在的场所会有更大的进步。</div><details style="color:orange;display:inline"><summary></summary>Now there are some who resist the new existence, even though they chose it, as long as possible. To some extent they must be present at birth, but they can still escape any full identification with the born infant. They hover within and about the form, but half reluctantly. There are many reasons for such behavior. Some personalities simply prefer in-between-life existence and are much more concerned with the theoretical solving of problems than the practical application necessarily involved. Others have discovered that physical existence does not meet their needs as well as they thought it would, and they will progress much better in other fields of reality and existence.</details><br>
<div style="display:inline">(10:48)可是，因着他们自己的特性，有些人格较喜欢在他们自身与其肉体存在之间设下一定的距离。他们对象征符号要关心得多，而把尘世生活看作是极具实验性的，可以说几乎是以一种猜疑的眼光来看它。他们对操纵物质的兴趣，还不如对概念在物质之内出现的方式更为好奇。</div><details style="color:orange;display:inline"><summary></summary>(10:48.) Because of their own characteristics, however, some prefer to set up a certain distance between themselves and their physical existences. They are much more concerned with symbols. They look upon earthly life as highly experimental. They approach it almost with a jaundiced eye, so to speak. They are not interested so much in manipulating matter as they are curious as to the ways in which ideas appear within matter.</details><br>
<div style="display:inline">一般来说，他们永远是对概念、哲学与捉摸不到的实相更感到自在。他们是思想者，于人于事总是有一点距离，他们的体型显示出肌肉的不发达。诗人和艺术家虽然也有一些这种天性，但一般说来是对尘世生活的物质价值有较深的赏识力，虽然他们有许多相同的特性。</div><details style="color:orange;display:inline"><summary></summary>Again generally speaking, they are always more at home with ideas, philosophies, and nontangible realities. They are thinkers always a bit apart, their body types showing a lack of muscular development. Poets and artists, while somewhat of this nature, as a rule are more deeply appreciative of the physical values of earthly existence, although they have many of the same characteristics.</details><br>
<div style="display:inline">所以，人对肉体的态度总是有所不同的，可能选择许多种不同的体型，但在全我方面总有一个笼统的偏好，并有主导全我的一些特征。因此通常所活过的各个不同的人生，还是有它自己的个人味道。</div><details style="color:orange;display:inline"><summary></summary>The attitude toward the body will always vary, therefore. Various types of bodies may be chosen, but there will still be overall preferences on the part of the whole self, and characteristics that will lead the whole self, so that generally the various lives lived will still have their own individual flavor.</details><br>
<div style="display:inline">如果不讨论人格离开肉体的方式的话，几乎不可能谈人格何时进入肉体，因为所有这一切都与个人特性及对物质实相的态度有极大的关系。与来生有关的决定不仅可在两世之间的状态达成，并且也在任一生的作梦状态里达成。</div><details style="color:orange;display:inline"><summary></summary>It is almost impossible to speak of when the personality enters the physical body without discussing the ways in which it leaves it, for all this is highly dependent upon personal characteristics and attitudes toward physical reality. Decisions as to future lives may be made not only in between-life conditions but also in dream states in any given life.</details><br>
<div style="display:inline">例如，你现在可能已经决定你下一次转世的环境。虽然在你来说，你的新父母可能现在仍是个婴儿，或在你的时间尺度下尚未出生，但仍能预作安排。</div><details style="color:orange;display:inline"><summary></summary>You may have already decided for example, now, upon the circumstances for your next incarnation. Although in your terms your new parents may be infants now, or in your scale of time not even born, the arrangements may still be made.</details><br>
<div style="display:inline">现在你可以休息一下。</div><details style="color:orange;display:inline"><summary></summary>Now you may take your break.</details><br>
<div style="display:inline">(“说得好极了。”)</div><details style="color:orange;display:inline"><summary></summary>(“That was very good.”</details><br>
<div style="display:inline">(11:00。珍的出神状态一直很深，她很难让她的眼睛保持睁开。“我喜欢他这么做——让我完全出去。。”她说，“但当我回来时我不知道自己在做什么……我真是出去了。”</div><details style="color:orange;display:inline"><summary></summary>(11:00 P.M. Jane’s trance had been deep. She had a time getting her eyes to stay open. “I like it when he does it like that ---- when I’m just out,” she said. “But when I come back I don’t know what I’m doing…. I was really out.”</details><br>
<div style="display:inline">(这次休息就结束了今晚写书的口授。赛斯给珍和我几页的个人资料作为结尾。)</div><details style="color:orange;display:inline"><summary></summary>(This break marked the end of book dictation for the evening. Seth finished the session by giving several pages of personal material for Jane and me.)</details><br>
<div style="display:inline">第十四章 创始的故事以及多次元的神</div><details style="color:orange;display:inline"><summary></summary>CHAPTER 14 STORIES OF THE BEGINNING, AND THE MULTIDIMENSIONAL GOD</details><br>
